keongom/keongom/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("services/", include("services.urls")),
    path("", include("services.urls", namespace="services")),  # ## services is the default app
]

keongom/services/urls.py
from django.urls import path

from . import views

app_name = "service"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:service_id>/", views.detail, name="detail"),
    path("<int:service_id>/polls/", views.polls, name="polls"),
    path("all.json", views.json, name="json"),  
]

keongom/services/models.py
import datetime

from django.utils import timezone
from django.db import models


class Service(models.Model):
    name_text = models.CharField(max_length=200)
    url_text = models.CharField(max_length=200)
    description_text = models.CharField(max_length=200)
    enabled_toggle = models.BooleanField()
    tls_toggle = models.BooleanField()
    
    def __str__(self):
        return self.name_text


class Poll(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    poll_date = models.DateTimeField("date polled")
    status_code = models.IntegerField(default=0)

    def __str__(self):
        return self.service.name_text + " - " + str(self.status_code) + " + " + str(self.poll_date)
    
    def was_polled_recently(self):
        return self.poll_date >= timezone.now() - datetime.timedelta(days=14)
    
    class Meta:
        get_latest_by = "poll_date"
        ordering = ["-poll_date"]

## TODO - Add a model for certificates information

keongom/services/views.py
import json

from django.shortcuts import render, get_object_or_404
from django.core import serializers
from django.http import HttpResponse, JsonResponse, Http404

from .models import Service


def index(request):
    service_list = Service.objects.filter(poll__isnull=False).distinct().order_by("name_text")
    context = {
        "service_list": service_list,
    }
    return render(request, "services/index.html", context)


def detail(request, service_id):
    service = get_object_or_404(Service, pk=service_id)
    # polls = service.poll_set.order_by("poll_date")[:5]  ## TODO: Why `5`?
    return render(request, "services/detail.html", {"service": service})


def polls(request, service_id):
    response = "You're looking at the polls of service %s."
    return render(response % service_id)

def json(request): ## Return a JSON response with enabled services and their latest poll status and poll date
    service_list = Service.objects.filter(poll__isnull=False).distinct().order_by("name_text")
    # response = serializers.serialize("json", service_list)
    response = []
    for service in service_list:
        latest_poll = service.poll_set.order_by("-poll_date").first()
        response.append({
            "name_text": service.name_text,
            "url_text": service.url_text,
            "status_code": latest_poll.status_code if latest_poll else None,
            "poll_date": latest_poll.poll_date if latest_poll else None,
        })
    return JsonResponse(response, safe=False)

keongom/services/templates/services/detail.html
{% extends 'services/layout.html' %}
{% block content %}
<p>&lt;- <a href="/">back to services</a></p>
<h2>Service details</h2>
<table class="table 
{% if service.enabled_toggle %}
    {% if service.poll_set.last.status_code == 200 %}table-success
    {% else %}table-danger
    {% endif %}
{% else %}table-secondary
{% endif %}
 table-striped">
    <tr>
        <th>Service</th>
        <td>{{ service.name_text }}</td>
    </tr>
    <tr>
        <td colspan="2">{{ service.description_text }}</td>
    </tr>
    <tr>
        <td colspan="2"><a href="{{ service.url_text }}">{{ service.url_text }}</a></td>
    </tr>
    <tr>
        <th>Monitoring</th>
        <td>{% if service.enabled_toggle %}enabled{% else %}disabled{% endif %}</td>
    </tr>
    <tr>
        <th>TLS monitoring</th>
        <td>{% if service.tls_toggle %}en{% else %}dis{% endif %}abled</td>
    </tr>
</table>
{% if service.poll_set %}
<hr/>
<p><b>Latest polls</b></p>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Date</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
{% for poll in service.poll_set.all %}
    <tr>
        <td>{{ poll.poll_date }}</td>
        <td {% if poll.status_code == 200 %}class="table-success"{% else %}class="table-danger"{% endif %}>{{ poll.status_code }}</td>
    </tr>
{% endfor %}
</table>
{% else %}
<h2>Never polled</h2>
{% endif %}
{% endblock %}

keongom/services/templates/services/index.html
{% extends 'services/layout.html' %}
{% block head %}
<meta http-equiv="refresh" content="300;">
{% endblock %}
{% block content %}
<h2>Services</h2>
{% if service_list %}
    <ul class="list-group">
    {% for service in service_list %}
        {% if service.enabled_toggle %}
            <li class="list-group-item d-flex justify-content-between align-items-start
            {% if service.poll_set.first.status_code == 200 %}list-group-item-success
                {% elif service.poll_set.first.status_code == 0 %}list-group-item-danger
            {% else %}list-group-item-warning{% endif %}">
                <div class="ms-2 me-auto">
                    <div class="fw-bold"><a href="{% url 'service:detail' service.id %}">{{ service.name_text }}</a></div>
                {% if service.poll_set.first.status_code == 200 %}online
                    {% elif service.poll_set.first.status_code == 0 %}offline
                    {% else %}status code {{ service.poll_set.first.status_code }}
                {% endif %} as of {{ service.poll_set.last.poll_date }}
                </div>
                <span class="badge text-bg-primary rounded-pill">{{ service.poll_set.first.status_code }}</span>
            </li>
        {% else %}
        <li class="list-group-item d-flex justify-content-between align-items-start list-group-item-secondary">
            <div class="ms-2 me-auto">
                <div class="fw-bold"><a href="{% url 'service:detail' service.id %}">{{ service.name_text }}</a></div>
                {{ service.name_text }} is disabled, but was last polled {{ service.poll_set.last.poll_date }}
            </div>
        </li>
        {% endif %}
    {% endfor %}
    </ul>
{% else %}
    <p>No services are available.</p>
{% endif %}
<hr/>
<p>Manage services in the admin backend.</p>
{% endblock %}

keongom/services/templates/services/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>KEONGOM Sentry</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'services/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'services/favicon-32x32.png' %}"/>
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'services/favicon-16x16.png' %}"/>
<link rel="manifest" href="{% static 'services/site.webmanifest' %}"/>
{% block head %}
{% endblock %}
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
        <img src="{% static 'services/favicon-32x32.png' %}" alt="Logo" width="32" height="32" class="d-inline-block align-text-top">
      HEONGOM Sentry
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/services">Services</a>
        <a class="nav-link" href="/services/all.json">JSON</a>
      </div>
    </div>
  </div>
</nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>